#!/bin/bash
# Test 3
# Check when inner marking is configured without marking its not activated
INTERFACE=$1
set policy qos profile prof bandwidth 2mbit
set policy qos name trunk shaper default prof
set policy qos name test shaper class 1 match 1 mark pcp-inner
set policy qos name test shaper class 1 profile prof
set policy qos name test shaper default prof
set int data $INTERFACE policy qos trunk
set int data $INTERFACE vif 10 inner-vlan 20
set int data $INTERFACE vif 10 policy qos test
set int data $INTERFACE vif 10 vlan 10
commit
ret=`run sh queuing $INTERFACE.10 class | grep markpcp | wc -l`
if [ $ret -ne 0 ]; then
   echo "Inner QinQ marking setup when no marking configured"
   exit 1;
fi

set policy qos name test shaper class 1 match 1 mark pcp 5
commit
ret=`run sh queuing $INTERFACE.10 class | grep markpcp | grep inner | grep active | wc -l`
if [ $ret -ne 1 ]; then
   echo "Inner QinQ marking setup failed"
   exit 1;
fi

# Tidy up
del int data $INTERFACE policy
del int data $INTERFACE vif 10
del policy
commit

echo "Test 3 passed"
